name: "Trigger"
on:
  push:
    branches:
      - main

jobs:
  run-updater:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2


      - name: Check for changes in backend
        id: changes
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q '^Backend/config/'; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "changes_detected=false" >> $GITHUB_ENV
          fi 
      - name: Echo based on changes detection
        run: |
          if [ "${{ env.changes_detected }}" == "true" ]; then
            echo "hello"
          else
            echo "bye"
          fi
